---

- name: Create uucp output directory
  command: mkdir /uucp-output creates=/uucp-output
  ignore_errors: yes
  sudo: yes

- name: Get uuchk results
  shell: /usr/lib/uucp/uuchk > /uucp-output/uuchk.log
  sudo: yes
  ignore_errors: yes

- name: Get uustat -a check results
  shell: uustat -a > /uucp-output/uustat-a.log
  sudo: yes
  ignore_errors: yes

- name: Get uustat -p check results
  shell: uustat -p > /uucp-output/uustat-p.log
  sudo: yes
  ignore_errors: yes

- name: Get uucp output directory
  fetch: src=/uucp dest={{ report_directory }}
  ignore_errors: yes

- name: Remove uucp output directory
  command: rm -rf /uucp-output removes=/uucp-output
  ignore_errors: yes
  sudo: yes